In [1]:
import tensorflow as tf
import numpy as np
print(tf.__version__)

2.0.0


In [2]:
# Construct a `Session` to execute the graph.
with tf.compat.v1.Session() as sess:

    # Build a dataflow graph.
    c = tf.constant([[1.0, 2.0], [3.0, 4.0]])
    d = tf.constant([[1.0, 1.0], [0.0, 1.0]])
    e = tf.matmul(c, d)

    # Execute the graph and store the value that `e` represents in `result`.
    result = sess.run(e)
    print(result)

[[1. 3.]
 [3. 7.]]


In [7]:
#use unintitialized value
with tf.compat.v1.Session() as sess:
    a = tf.constant(np.ones((2, 2), dtype = np.float32))
    b = tf.Variable(tf.ones((2, 2)))
    c = a@b
    result = sess.run(c)
    print(result)

Instructions for updating:
If using Keras pass *_constraint arguments to layers.


FailedPreconditionError: Error while reading resource variable Variable from Container: localhost. This could mean that the variable was uninitialized. Not found: Container localhost does not exist. (Could not find resource: localhost/Variable)
	 [[node matmul/ReadVariableOp (defined at d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\framework\ops.py:1751) ]]

Original stack trace for 'matmul/ReadVariableOp':
  File "d:\users\figohjs\appdata\local\continuum\anaconda3\Lib\runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "d:\users\figohjs\appdata\local\continuum\anaconda3\Lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\ipykernel_launcher.py", line 16, in <module>
    app.launch_new_instance()
  File "d:\users\figohjs\documents\testenv\lib\site-packages\traitlets\config\application.py", line 664, in launch_instance
    app.start()
  File "d:\users\figohjs\documents\testenv\lib\site-packages\ipykernel\kernelapp.py", line 583, in start
    self.io_loop.start()
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\platform\asyncio.py", line 132, in start
    self.asyncio_loop.run_forever()
  File "d:\users\figohjs\appdata\local\continuum\anaconda3\Lib\asyncio\base_events.py", line 539, in run_forever
    self._run_once()
  File "d:\users\figohjs\appdata\local\continuum\anaconda3\Lib\asyncio\base_events.py", line 1775, in _run_once
    handle._run()
  File "d:\users\figohjs\appdata\local\continuum\anaconda3\Lib\asyncio\events.py", line 88, in _run
    self._context.run(self._callback, *self._args)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\ioloop.py", line 758, in _run_callback
    ret = callback()
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\stack_context.py", line 300, in null_wrapper
    return fn(*args, **kwargs)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\gen.py", line 1233, in inner
    self.run()
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\gen.py", line 1147, in run
    yielded = self.gen.send(value)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\ipykernel\kernelbase.py", line 361, in process_one
    yield gen.maybe_future(dispatch(*args))
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\ipykernel\kernelbase.py", line 268, in dispatch_shell
    yield gen.maybe_future(handler(stream, idents, msg))
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\ipykernel\kernelbase.py", line 541, in execute_request
    user_expressions, allow_stdin,
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tornado\gen.py", line 326, in wrapper
    yielded = next(result)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\ipykernel\ipkernel.py", line 300, in do_execute
    res = shell.run_cell(code, store_history=store_history, silent=silent)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\ipykernel\zmqshell.py", line 536, in run_cell
    return super(ZMQInteractiveShell, self).run_cell(*args, **kwargs)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\IPython\core\interactiveshell.py", line 2858, in run_cell
    raw_cell, store_history, silent, shell_futures)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\IPython\core\interactiveshell.py", line 2886, in _run_cell
    return runner(coro)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\IPython\core\async_helpers.py", line 68, in _pseudo_sync_runner
    coro.send(None)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\IPython\core\interactiveshell.py", line 3063, in run_cell_async
    interactivity=interactivity, compiler=compiler, result=result)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\IPython\core\interactiveshell.py", line 3254, in run_ast_nodes
    if (await self.run_code(code, result,  async_=asy)):
  File "d:\users\figohjs\documents\testenv\lib\site-packages\IPython\core\interactiveshell.py", line 3331, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-7-1a5bd6618bcd>", line 4, in <module>
    c = a@b
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\ops\math_ops.py", line 903, in binary_op_wrapper
    y, dtype_hint=x.dtype.base_dtype, name="y")
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1242, in convert_to_tensor_v2
    as_ref=False)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1284, in internal_convert_to_tensor
    value, dtype=preferred_dtype, name=name, as_ref=as_ref)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 1789, in _dense_var_to_tensor
    return var._dense_var_to_tensor(dtype=dtype, name=name, as_ref=as_ref)  # pylint: disable=protected-access
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 1214, in _dense_var_to_tensor
    return self.value()
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 524, in value
    return self._read_variable_op()
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\ops\resource_variable_ops.py", line 608, in _read_variable_op
    self._dtype)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\ops\gen_resource_variable_ops.py", line 586, in read_variable_op
    "ReadVariableOp", resource=resource, dtype=dtype, name=name)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\framework\op_def_library.py", line 793, in _apply_op_helper
    op_def=op_def)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\util\deprecation.py", line 507, in new_func
    return func(*args, **kwargs)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3360, in create_op
    attrs, op_def, compute_device)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 3429, in _create_op_internal
    op_def=op_def)
  File "d:\users\figohjs\documents\testenv\lib\site-packages\tensorflow_core\python\framework\ops.py", line 1751, in __init__
    self._traceback = tf_stack.extract_stack()


In [10]:
#initialize value before use
with tf.compat.v1.Session() as sess:
    a = tf.constant(np.ones((2, 2), dtype = np.float32))
    b = tf.Variable(tf.ones((2, 2)))
    c = a@b
    sess.run(tf.compat.v1.global_variables_initializer())
    result = sess.run(c)
    print(result)

[[2. 2.]
 [2. 2.]]


In [22]:
tf.compat.v1.reset_default_graph()
#feeding placeholder value
with tf.compat.v1.Session() as sess:
    a = tf.compat.v1.placeholder(np.float32, (2, 2))
    b = tf.Variable(tf.ones((2, 2)))
    c = a@b
    sess.run(tf.compat.v1.global_variables_initializer())
    result = sess.run(c, feed_dict = {a:np.ones((2,2))})
    print(result)    

[[2. 2.]
 [2. 2.]]


In [63]:
#optimiser
#defining f as a function of x:x^2
tf.compat.v1.reset_default_graph()
x = tf.compat.v1.get_variable("x", shape = (), dtype = tf.float32)
f = x**2

#disable eager execution for tensorflow v1
#v2 onwards has eager execution
tf.compat.v1.disable_v2_behavior()
#learning rate is 0.1
#apply gradient descent to minmize f w.r.t x
optimizer = tf.compat.v1.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f, var_list = [x])

#running session
with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    for i in range(10):
#         _, curr_x, curr_f = sess.run([step, x, f])
#         print(curr_x, curr_f)
        print(sess.run([step, x, f]))

[None, -0.16535893, 0.042724334]
[None, -0.13228714, 0.027343577]
[None, -0.105829716, 0.017499888]
[None, -0.08466377, 0.011199929]
[None, -0.067731015, 0.007167954]
[None, -0.054184813, 0.0045874906]
[None, -0.04334785, 0.002935994]
[None, -0.03467828, 0.0018790362]
[None, -0.027742624, 0.0012025831]
[None, -0.022194099, 0.0007696532]


In [26]:
#list out trainable variables
tf.compat.v1.trainable_variables()

[<tf.Variable 'x:0' shape=() dtype=float32_ref>]

In [96]:
tf.compat.v1.reset_default_graph()
x = tf.compat.v1.get_variable("x", shape = (), dtype = tf.float32)
f = x**2

# #disable eager execution for tensorflow v1
# #v2 onwards has eager execution
#tf.compat.v1.disable_v2_behavior()
# #learning rate is 0.1
#apply gradient descent to minmize f w.r.t x
optimizer = tf.compat.v1.train.GradientDescentOptimizer(0.1)
step = optimizer.minimize(f, var_list = [x])

#logging tensorflow immediate results aka TensorBoard
summary1 = tf.summary.scalar('curr_x', x)
summary2 = tf.summary.scalar('curr_f', f)
summaries = tf.summary.merge([summary1, summary2])
#summaries = tf.contrib.summary()

with tf.compat.v1.Session() as sess:
    sess.run(tf.compat.v1.global_variables_initializer())
    summary_writer = tf.compat.v1.summary.FileWriter("logs/1", sess.graph)

    for i in range(10):
        #_, curr_summaries = sess.run([step, summaries])
        print(sess.run([step, summaries]))
        #summary_writer.add_summaries(curr_summaries, i)
        #summary_writer.flush()

AttributeError: module 'tensorflow_core.summary' has no attribute 'merge'

In [91]:
tf.compat.v1.reset_default_graph()

# create graph
a = tf.constant(2, name="a")
b = tf.constant(3, name="b")
c = tf.add(a, b, name="addition")

# creating the writer out of the session
# writer = tf.summary.FileWriter('./graphs', tf.get_default_graph())

# launch the graph in a session
with tf.compat.v1.Session() as sess:
    # or creating the writer inside the session
    writer = tf.compat.v1.summary.FileWriter('./graphs', sess.graph)
    print(sess.run(c))

5


In [92]:
from tensorboard import program
tb = program.TensorBoard()
tb.configure(argv=[None, '--logdir', "./graphs"])
url = tb.launch()